In [2]:
import numpy as np

    在这些方法中，布尔值中的True和False会被相应地转换为1和0参与计算

-amin(a[, axis, out, keepdims])

        返回数组的最小值或沿轴的最小值

-amax(a[, axis, out, keepdims])

        返回数组的最大值或沿轴的最大值

-nanmin(a[, axis, out, keepdims])

        返回数组的最小值或沿轴的最小值，忽略任何NAN

-nanmax(a[, axis, out, keepdims])

        返回数组的最大值或沿轴方向的最大值，忽略任何NAN

-median(a[, axis, out, overwrite_input, keepdims])

        沿指定轴计算中值

-average(a[, axis, weights, returned])

        计算沿指定轴的加权平均

-mean(a[, axis, dtype, out, keepdims])

        沿指定的轴计算算术平均值

-std(a[, axis, dtype, out, ddof, keepdims])

        计算沿指定轴的标准偏差

-var(a[, axis, dtype, out, ddof, keepdims])

        计算沿指定轴的方差

-nanmedian(a[, axis, out, overwrite_input, …])

        在忽略NAS的情况下，沿指定的轴计算中值

-nanmean(a[, axis, dtype, out, keepdims])

        计算沿指定轴的算术平均值，忽略NAN

-nanstd(a[, axis, dtype, out, ddof, keepdims])

        计算指定轴上的标准偏差，而忽略NAN

-nanvar(a[, axis, dtype, out, ddof, keepdims])

        计算指定轴上的方差，同时忽略NAN

In [3]:
arr = np.array([[np.NaN, 0, 1, 2, 3],
                [ 4, 5, np.NaN, 6, 7],
                [ 8, 9, 10, np.NaN, 11]])
arr

array([[nan,  0.,  1.,  2.,  3.],
       [ 4.,  5., nan,  6.,  7.],
       [ 8.,  9., 10., nan, 11.]])

In [4]:
np.amax(arr)

nan

In [5]:
np.nanmax(arr)

11.0

In [13]:
np.nanmin(arr, axis=0)  # 默认是计算flatten之后的数组，可以指定axis参数 0/1

array([4., 0., 1., 2., 3.])

In [16]:
np.nanmean(arr, axis=0) #平均值

array([6.        , 4.66666667, 5.5       , 4.        , 7.        ])

In [17]:
np.nanmedian(arr) #中位数

5.5

In [18]:
np.nanstd(arr)  #标准差

3.452052529534663

In [19]:
np.nanvar(arr)  #方差

11.916666666666666