In [1]:
import numpy as np

数组形状变换
重塑
扁平化处理
数组合并
数组拆分
数组扩充
数组转置和轴对换

### 1.重塑

ndarray.reshape(shape, order='c')  #reshape 函数返回修改后的新对象,order默认为‘C’ ，按列读取
ndarrray.resize()  #ndarray.resize 方法修改数组本身
重塑的各个维度上整数的乘积必须等于arr.size
如果想自动计算某个轴上的大小，可以传入-1

In [3]:
arr = np.arange(12)
arr2 = arr.copy()

In [4]:
arr.reshape((4, 3))  #order默认为‘C’ ，按列读取

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
arr.reshape((4, 3), order='F')   # 按行读取

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [6]:
arr  #本身无变化

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
arr2.resize((4, 3))  # resize()会修改对象本身
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

多维数组重塑

In [11]:
ndarr = arr.reshape(3, 4)
ndarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
ndarr.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
ndarr.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

##扁平化处理

In [15]:
ndarr = np.arange(12).reshape(4, 3)
ndarr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
ndarr.flatten()  # 默认order='C'，按列

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
ravel_ndarr = ndarr.ravel() # flatten()返回新对象，ravel()返回视图
ravel_ndarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
ravel_ndarr[0] = -1
ndarr

array([[-1,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
3.数组合并

In [31]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]]


In [32]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
b.T

array([[5],
       [6]])

In [34]:
a.shape, b.T.shape

((2, 2), (2, 1))

In [35]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10, 20, 30],
              [40, 50, 60]])
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [36]:
np.row_stack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [37]:
np.hstack((a, b))

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [38]:
np.column_stack((a, b))

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [39]:
np.dstack((a, b))

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]]])

4.数组拆分

In [41]:
split_arr = np.arange(36).reshape(-1, 6)
split_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [53]:
a, b, c = np.split(split_arr, 3, axis=0)
print("a:\n",a)
print("b:\n",b)
print("c:\n",c)

a:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
b:
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
c:
 [[24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [54]:
a, b, c = np.split(split_arr, 3, axis=1)
print("a:\n",a)
print("b:\n",b)
print("c:\n",c)

a:
 [[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]
 [24 25]
 [30 31]]
b:
 [[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]
 [26 27]
 [32 33]]
c:
 [[ 4  5]
 [10 11]
 [16 17]
 [22 23]
 [28 29]
 [34 35]]


5.repeat和title

In [56]:
#repeat--针对元素
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [57]:
np.repeat(arr, 2)

array([0, 0, 1, 1, 2, 2, 3, 3])

In [59]:
np.repeat(arr,[1,2,3,4]) # 指定每个元素的重复次数

array([0, 1, 1, 2, 2, 2, 3, 3, 3, 3])

In [60]:
#title针对整个数组
arr

array([0, 1, 2, 3])

In [62]:
np.tile(arr, 2) # 对标量是横向扩展

array([0, 1, 2, 3, 0, 1, 2, 3])

In [63]:
np.tile(arr, (2,3))

array([[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]])

6.数组转置和轴对换

In [64]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [66]:
arr.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])