广播（Broadcast）
-
广播是指不同形状的数组之间的算术运算的执行方式。受限于某些约束，较小的数组依据较大数组“broadcasting”，使得它们具有兼容的形状。


广播的原则
-
如果两个数组的后缘维度（即从末尾开始算起的维度）的轴长度相符或其中一方的长度为1，则认为它们是广播兼容的。广播会在缺失和（或）长度为1的维度上进行。

    让所有输入数组都向其中形状最长的数组看齐，形状中不足的部分都通过在前面加 1 补齐。
    输出数组的形状是输入数组形状的各个维度上的最大值。
    如果输入数组的某个维度和输出数组的对应维度的长度相同或者其长度为 1 时，这个数组能够用来计算，否则出错。
    当输入数组的某个维度的长度为 1 时，沿着此维度运算时都用此维度上的第一组值。

In [24]:
import numpy as np

In [25]:
arr1 = np.arange(24).reshape(3,4,2)
arr2 = np.array([[4],
                [4],
                [4],
                [4]])
print(arr1)
print(arr2)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[4]
 [4]
 [4]
 [4]]


In [27]:
arr3 = arr1 - arr2
arr3

array([[[-4, -3],
        [-2, -1],
        [ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [28]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(3, 4, 2)
(4, 1)
(3, 4, 2)


In [ ]:
伪随机数生成

numpy.random模块对Python内置的random进行了补充，增加了一些用于高效生成多种概率分布的样本值的函数

之所以被称作伪随机数而不是随机数是因为它们都是通过算法基于随机数生成器种子在确定性的条件下生成的

常用函数：


rand
        产生指定形状的均匀分布的样本值

randint

        从给定的上下限范围内选取随机整数

randn

        产生正态分布（平均值为0，标准差为1）的样本值，类似于MATLAB接口

binomial

        产生二项分布的样本值

normal

        产生正态（高斯）分布的样本值

beta

        产生Beta分布的样本值

chisquare

        产生卡方分布的样本值

gamma

        产生Gamma分布的样本值

uniform

        产生在指定范围中均匀分布的样本值

seed

        确定随机数生成器的种子

permutation

        返回一个序列的随机排列或返回一个随机排列的范围

shuffle

        对一个序列就地随机排列

In [12]:
arr1 = np.random.randint(5, size=(3, 4))
arr1

array([[1, 3, 1, 1],
       [1, 2, 0, 2],
       [1, 2, 4, 2]])

In [8]:
np.random.randn(3, 4)

array([[-0.16555474,  0.59585598, -2.43430598,  0.37632891],
       [-0.92159874,  0.17951412,  0.77380286,  1.131176  ],
       [ 0.91202267,  0.01128431, -1.41149089,  0.32030475]])

In [9]:
# 生成指定范围的样本值
np.random.uniform(1, 2, 100)

array([1.26897217, 1.29310154, 1.92313216, 1.8546961 , 1.33356015,
       1.28472969, 1.048164  , 1.98602744, 1.91974932, 1.64350952,
       1.07475065, 1.06937271, 1.09894941, 1.96378942, 1.81328461,
       1.86333773, 1.49959015, 1.99632028, 1.29704332, 1.42030692,
       1.93064203, 1.24428842, 1.48269997, 1.62717812, 1.73669758,
       1.73069701, 1.2720035 , 1.9027611 , 1.00180347, 1.79882837,
       1.49085526, 1.33160793, 1.93674565, 1.86839662, 1.4907762 ,
       1.06646706, 1.09300343, 1.82373031, 1.19347742, 1.08714153,
       1.68529718, 1.37146371, 1.48302326, 1.07630521, 1.22935948,
       1.59718342, 1.68411916, 1.65938013, 1.59535112, 1.266549  ,
       1.8317311 , 1.03934284, 1.06869713, 1.26732218, 1.9227461 ,
       1.77185869, 1.50067521, 1.52781788, 1.1096475 , 1.73447299,
       1.77258681, 1.41065899, 1.68495321, 1.81541755, 1.36798674,
       1.55562302, 1.61558923, 1.33870204, 1.73725936, 1.15721077,
       1.22693338, 1.06281092, 1.9217784 , 1.024435  , 1.78727