#通用函数

通用函数（或简称为ufunc）是一种以元素为单位对ndarray进行操作的函数，支持数组广播，类型转换和其他一些标准特性。 也就是说，ufunc是一个函数的“矢量化”包装器，它接受固定数量的特定输入并产生固定数量的特定输出
在NumPy中，通用函数是numpy.ufunc类的实例

https://docs.scipy.org/doc/numpy/reference/ufuncs.html

一元ufunc

       函数	                          说明
       
    abs、fabs	计算整数、浮点数或复数的绝对值。对于非复数值，可以使用更快的fabs
    
    sqrt	     计算各元素的平方根。相当于arr ** 0.5
    
    square	     计算各元素的平方。相当于arr ** 2
    
    exp	         计算各元素的指数。相当于e的x次方
    
    log、log10、log2、log1p	      分别对应自然对数（底数为e）、底数为10的log、底数为2的log、log(1 + p)
    
    sign	     计算各元素的正负号：1（正数）、0（零）、-1（负数）
    
    ceil	     计算各元素的ceiling值，即大于等于该值的最小整数
    
    floor	     计算各元素的floor值。即小于等于该值的最大整数
    
    rint	     将各元素值四舍五入到最接近的整数，保留dtype
    
    modf	     将数组的小数和整数部分以两个独立数组的形式返回
    
    isnan	     返回一个表示“哪些值是NaN”的布尔型数组
    
    isfinite、isinf	                                   分别返回一个表示“哪些元素是有穷的（非inf，非NaN）”或“哪些元素是无穷的”的布尔型数组
     
    cos、cosh、sin、sinh、tan、tanh	                   普通型和双曲型三角函数
    
    arccos、arccosh、arcsin、arcsinh、arctan、arctanh   反三角函数
    
    logical_not	                                        计算个元素的not x的真值。相当于-arr
    
    
    
    
二元ufunc

    函数	                            说明
    
    add	                       将数组中对应的元素相加
    
    subtract	               从第一个数组中减去第二个数组中的元素
    
    multiply	               将数组元素相乘
    
    divide、floor_divide    	  除法或向下取整除法（丢弃余数）
    
    power	                   对第一个数组中的元素A，根据第二个数组中的相应元素B，计算A的B次方
    
    maximum、fmax	          元素级的最大值计算。fmax将忽略NaN
    
    minimum、fmin	          元素级的最小值计算。fmin将忽略NaN
    
    mod	                       元素级别的求模计算（除法的余数）
    
    copysign	               将第二个数组中的值得符号复制给第一个数组中的值
    
    greater、greater_equal、less、less_equal、equal、not_equal、	执行元素级的比较运算，最终产生布尔数组。相当于中缀运算符号>、>=、<、<=、==、!=
    
    logical_and、logical_or、logical_xor	                        执行元素级的真值逻辑运算。相当于中缀运算符&、| 、^


#常用的函数

-diagonal(v, k=0)

            以一维数组的形式返回方阵的对角线（或非对角线）元素，或将一维数组转换为方阵（非对角线元素为0）

-dot(a, b[, out])

            两个数组的点积

-trace(a[, offset, axis1, axis2, dtype, out])

            计算对角线元素的和

-linalg.det(a)

            计算矩阵行列式

-linalg.inv(a)

            计算方阵的逆

In [1]:
import numpy as np
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
arr.diagonal() 
np.diag(arr, k=0)  #两者等价 默认k = 0

array([0, 4, 8])

In [13]:
diag_arr = np.array([1, 2, 3])
np.diag(diag_arr)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
# 计算矩阵乘积
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]

np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [15]:
# 计算对角线元素的和
np.trace(arr)

12

In [20]:
# 计算矩阵行列式
arr2 = np.array([[1, 2],
                 [3, 4]])
np.linalg.det(arr2)

-2.0000000000000004

In [21]:
# 计算矩阵的逆
np.linalg.inv(arr2)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [24]:
arr2.T

array([[1, 3],
       [2, 4]])