In [1]:
import numpy as np

arr = [[1, 2, 3],
       [4, 5, 6]]
 
ndarr = np.array(arr)
ndarr

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
ndarr.shape

(2, 3)

In [4]:
ndarr.size

6

In [7]:
ndarr.ndim    #数组的轴（维度）的个数。维度的数量被称为rank。

2

In [9]:
ndarr.dtype  #一个描述数组中元素类型的对象

dtype('int32')

In [10]:
ndarr.itemsize  #数组中每个元素的字节大小。

4

#ndarry创建方式

In [11]:
data = [[1,2,3], [4,5,6]]
arr1 = np.array(data)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.zeros([2, 3])  #ones类似

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
np.zeros_like(arr1)

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
arr2 = np.asarray(arr1) 
arr2
#array()和asarray()都可以将结构数据转化为ndarray，
#但是主要区别就是当数据源是ndarray时，array仍然会copy出一个副本，占用新的内存，但asarray不会

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr3 = np.empty([2, 3])
arr3        #根据指定形状创建ndarray对象，只分配内存但是不填充任何值

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
arr3 = np.empty_like(data)
arr3        #根据指定形状创建ndarray对象，只分配内存但是不填充任何值


array([[916,   0, 916],
       [  0,   0,   0]])

In [36]:
arr4 = np.full([2, 3], fill_value=(1,2,3))
arr4

array([[1, 2, 3],
       [1, 2, 3]])

In [39]:
arr4 = np.full_like(data, 1)
arr4

array([[1, 1, 1],
       [1, 1, 1]])

In [40]:
# numpy.identity(n, dtype=None)传入一个整数N，创建一个N * N的单位矩阵
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
arr5 = np.eye(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
arr6 = np.random.randn(2, 3)
arr6

array([[ 0.20517142,  0.18623077, -0.54569016],
       [ 2.14840996, -0.94878768,  1.29897964]])

In [51]:
"""
参数
start：开始位置，数字，可选，默认值为0
stop：结束位置，数字，
step：步长，数字，可选，默认为1。如果指定step则必须指定start
dtype：类型。不指定则自动推断
"""
arr7 = np.arange(start=0, stop=10, step=2, dtype='float32')
arr7

array([0., 2., 4., 6., 8.], dtype=float32)

In [53]:
arr7 = np.linspace(0, 10, 5)
arr7

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [54]:
def fun(x, y):
    return x * 10 + y**2

np.fromfunction(fun, (4, 5), dtype=np.int)

array([[ 0,  1,  4,  9, 16],
       [10, 11, 14, 19, 26],
       [20, 21, 24, 29, 36],
       [30, 31, 34, 39, 46]])

In [55]:
np.fromfunction(lambda i,j:i+j,(2, 3))

array([[0., 1., 2.],
       [1., 2., 3.]])