In [1]:
import numpy as np

#数据类型NumPy的数据类型
1.ndarray对象的dtype属性中描述了该对象的数据类型信息，返回一个dtype对象
2.调用astype()会创建一个新对象，不会改变原对象
3.所有的数据类型如下表所示：
数据类型	       类型代码	              说明
int8、uint8	    i1、u1	有符号和无符号的8位（1个字节）整形
int16、uint16	i2、u2	有符号和无符号的16位（2个字节）整形
int32、uint32	i4、u4	有符号和无符号的32位（4个字节）整形
int64、uint64	i8、u8	有符号和无符号的64位（8个字节）整形
float16	            f2	  半精度浮点数
float32	          f4或f	  标准的单精度浮点数
float64	          f8或d	  标准的双精度浮点数
float128	      f16或g	  扩展精度浮点数
bool	             ?	   存储布尔类型（存储为一个字节）
object	             O	   Python对象类型
string_	             S	   固定长度的字符串类型（每个字符1个字节）
unicode_	         U	   固定长度的unicode类型（字节数由平台决定）

complex64、complex128、complex256	
c8、c16、c32	
分别用两个32位、64位或128位浮点数表示的复数


注意：int_为int32的简写，float_为float64的简写，complex_为complex128的简写

In [2]:
arr1 = np.array([1.0, 3.5, 6.6, 10.0])
arr1

array([ 1. ,  3.5,  6.6, 10. ])

In [3]:
arr1.astype('int') #通过astype()方法转换数据类型

array([ 1,  3,  6, 10])

In [6]:
#调用dtype的mro方法即可查看其所有的父类
np.int32.mro()

[numpy.int32,
 numpy.signedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

#拷贝

NumPy中拷贝分为三种情况：

-完全不拷贝

        一个数组的任何变化都反映在另一个数组上，包括值变化和形状变化

-浅拷贝

        一个数组值会变化会反映在另一个数组上，但是形状不变化

-深拷贝

        创建原数组的副本，副本的任何变化都不会反映在原数组上

In [13]:
# 完全不拷贝
a = np.arange(12)
b = a
print(a)
print(b)

a is b

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


True

In [14]:
a = np.arange(12)
c = a.view()
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
c is a

False

In [16]:
c.base is a

True

In [18]:
c[2] = 0 #浅拷贝改变了数值
print(a)
print(c)

[ 0  1  0  3  4  5  6  7  8  9 10 11]
[ 0  1  0  3  4  5  6  7  8  9 10 11]


In [19]:
c.shape = (12, 1) #浅拷贝未改变形状
print(a)
print(c)

[ 0  1  0  3  4  5  6  7  8  9 10 11]
[[ 0]
 [ 1]
 [ 0]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [29]:
# 深拷贝
a = np.arange(12)
d = a.copy()
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
d is a

False

In [22]:
d.base is a

False

In [30]:
a[1] = 0
print(a)
print(d)

[ 0  0  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [25]:
d.shape = (12, 1)
print(a)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
